version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bouteeq
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    ports:
      - 5432:5432

  cache:
    image: redis:7.4.0-alpine
    command: --port 6380
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "--raw", "incr", "ping"]
    ports:
      - 6380:6380

#  queue:
#    image: rabbitmq
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=secret'
#      - 'RABBITMQ_DEFAULT_USER=myuser'
#    ports:
#      - 5672:5672
#      - 15672:15672

  backend:
    build:
      context: ./bouteek-backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./bouteek-frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
    ports:
      - 80:80

volumes:
  postgres_data:

